// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "./Core.res.mjs";

function useFetch(domainName, headers) {
  return {
          get: Core.get(domainName, headers),
          post: Core.create(domainName, headers),
          put: Core.update(domainName, headers),
          delete: Core.delete_(domainName, headers)
        };
}

var Internal;

export {
  Internal ,
  useFetch ,
}
/* No side effect */
