// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_promise from "rescript/lib/es6/js_promise.js";
import * as ParaSwapApi from "./ParaSwapApi.res.mjs";

function formatAmount(amountStr, decimals) {
  var len = amountStr.length;
  if (len <= decimals) {
    var zerosNeeded = decimals - len | 0;
    var zeros = "0".repeat(zerosNeeded);
    return "0." + zeros + amountStr;
  }
  var integerPart = amountStr.slice(0, len - decimals | 0);
  var fractionalPart = amountStr.slice(len - decimals | 0, len);
  return integerPart + "." + fractionalPart;
}

var toToken = "DAI";

var swapDetailsPromise = ParaSwapApi.getSwapDetails("ETH", toToken, "1000000000000000000", "https://apiv5.paraswap.io/swap", "1", "0xc03Fa33F7E9EA5EF7a2b5ecfa6533ad80Eb358A0");

Js_promise.then_((function (res) {
        if (res.TAG === "Ok") {
          console.log("Swap rate data:");
          var formattedAmount = formatAmount(res._0.priceRoute.destAmount, 18);
          console.log("Montant reçu : " + formattedAmount + " " + toToken);
          return Promise.resolve();
        }
        console.error("Error fetching swap rate:");
        console.error(res._0);
        return Promise.resolve();
      }), swapDetailsPromise);

export {
  formatAmount ,
}
/* swapDetailsPromise Not a pure module */
